import { definePack, detect, dim } from './kit';

/** Spec §3.3.2 — Biology. */
export const bioPack = definePack({
  id: 'bio',
  name: 'Biology',
  shortName: 'Bio',
  glyph: 'glyph-bio',
  tagline: 'The band is on the gel. What does it actually rule out?',
  materialKinds: ['lab reports', 'research summaries', 'genetics / molecular / cell / ecology essays', 'figure legends', 'protocols'],
  detect: detect(
    [['PCR', 3], ['Western', 3], ['qPCR', 3], ['knockout', 3], ['allele', 3], ['phenotype', 3],
     ['assay', 2], ['primer', 3], ['negative control', 3], ['expression', 2], ['ecology', 2],
     ['species', 2], ['ANOVA', 1], ['in vitro', 2], ['transfect', 3], ['incubat', 2], ['buffer', 1]],
    [['\\bfold[- ]change\\b', 3], ['\\bp\\s*[<=]\\s*0\\.', 1], ['\\bn\\s*=\\s*\\d+', 1],
     ['^\\s*(Methods|Results|Discussion)\\b', 2]],
  ),
  dimensions: [
    dim('mechanism', 'Mechanism at the right scale', 'Molecular → cellular → organism causal chain without conflating levels.',
      ['Ask them to climb one level up and one level down.',
       'Ask which step in the chain their own data actually observed.'],
      'Moves between scales and marks which step was measured.', 'Narrates a textbook pathway in textbook order.'),
    dim('controls', 'Experimental logic', 'What each control rules out — and does not.',
      ['Name exactly what this control excludes, and one failure it does not exclude.',
       'Ask what the assay physically measures versus what the sentence claims.'],
      'Separates the physical measurement from the interpretive claim.', 'Says the control "shows the experiment worked".'),
    dim('data2claim', 'Data-to-claim', 'Does Figure N support the sentence; n, replicates, variance, effect size.',
      ['Point to the panel that carries this sentence.',
       'Ask what one ambiguous band does to the claim.'],
      'Ties each claim to a panel and states what would weaken it.', 'Cites "the results" without a panel.'),
    dim('methodchoice', 'Method choice', 'Why this assay / organism / model over another.',
      ['Name a result the alternative assay would show that this one cannot.'],
      'Names what the alternative would reveal.', '"It is the standard method in the field."'),
    dim('precision', 'Terminology precision', 'Gene vs protein vs allele; expression vs abundance vs activity.',
      ['Ask for the difference between two terms they used interchangeably.'],
      'Draws the distinction and says which one was measured.', 'Uses the terms as synonyms.'),
    dim('perturbation', 'Perturbation prediction', 'Knockdown efficiency, temperature, pH, dose → predicted figure.',
      ['If the knockdown were only 40% efficient, what would Figure 2 look like?'],
      'Predicts a specific, checkable change to their own figure.', 'Says the effect would be "reduced".'),
    dim('provenance', 'Provenance of specifics', 'This concentration, this Tm, this fold-change, this p-value, this species.',
      ['Where did this number come from and what is it sensitive to?'],
      'Explains the choice and its tolerance.', '"It is what the protocol said."'),
    dim('limits', 'Limitations owned', 'What would falsify the conclusion; the experiment not run.',
      ['Name the single experiment that would most threaten your conclusion.'],
      'Names a falsifier and why it was not run.', 'Writes "further studies are needed".'),
  ],
  counterfactualLevers: [
    'remove or swap a control', '40% knockdown instead of complete', 'halve n',
    'different tissue or organism', 'change temperature or pH', 'a band appears in the negative control',
  ],
  tells: [
    'mechanism narrated in textbook order but never linked to the student’s own figure',
    '"statistically significant" with no test or n',
    'every hedge in place ("these results suggest… further studies are needed")',
    'results describing what a control should show rather than what it showed',
    'flawless nomenclature paired with scale errors',
    'classic experiments cited that were not on the syllabus',
    'discussion generalising beyond the organism studied',
  ],
  vocabularyTraps: ['upregulated', 'significant', 'pathway', 'expression', 'homeostasis', 'selective pressure', 'control'],
  languageNote: 'Quote the student’s own sentence or figure legend verbatim. Refer to figures by the label the student used.',
  sampleProbes: [
    'Your negative control lane shows no band. Which failure does that rule out — and name one it does not.',
    'You wrote expression "increased 2.3-fold". What did the instrument measure, and what two assumptions turn that into "expression"?',
    'If the knockdown were only 40% efficient, what would you expect in Figure 2 — and does Figure 2 look like that?',
    'Why a Western here rather than qPCR? Name a result the Western shows that qPCR would miss.',
    'Your discussion says the enzyme "is more active at 37 °C". More active or more abundant — which did your assay measure?',
  ],
});
