import { definePack, detect, dim } from './kit';

/** Spec §3.3.7 — Chemistry. */
export const chemPack = definePack({
  id: 'chem',
  name: 'Chemistry',
  shortName: 'Chem',
  glyph: 'glyph-chem',
  tagline: '62% yield. Where did the other 38% go?',
  materialKinds: ['lab reports (synthesis, titration, kinetics)', 'mechanism problem sets', 'spectral analyses'],
  detect: detect(
    [['yield', 3], ['mmol', 4], ['reflux', 4], ['NMR', 4], ['ppm', 3], ['IR ', 2], ['TLC', 4],
     ['reagent', 3], ['nucleophile', 4], ['equilibrium', 2], ['titration', 4], ['molarity', 3],
     ['SN2', 4], ['workup', 4], ['recrystalli', 4], ['stoichiometr', 3]],
    [['\\b\\d+(\\.\\d+)?\\s*mol\\b', 3], ['\\b\\d+(\\.\\d+)?\\s*°C\\b', 2], ['\\bδ\\s*\\d', 3]],
  ),
  dimensions: [
    dim('mechanism', 'Mechanism', 'Intermediates, rate-determining step, why the arrows go that way for this substrate.',
      ['Why this mechanism for THIS substrate rather than the textbook default?'],
      'Adapts the mechanism to the substrate and names the RDS.', 'Draws the textbook mechanism unchanged.'),
    dim('conditions', 'Reagent & condition choice', 'Why this reagent, solvent and temperature.',
      ['Why 0 °C — what would you see at room temperature?'],
      'Predicts the observable consequence of the change.', 'Says the condition is "standard".'),
    dim('quant', 'Quantitative provenance', 'Limiting reagent, stoichiometry, yield, concentration — recomputed aloud.',
      ['Recompute the limiting reagent from your masses, out loud.'],
      'Recomputes live and catches their own rounding.', 'Reads the number off the report.'),
    dim('characterization', 'Characterisation-to-claim', 'Why this peak or band means that structure.',
      ['The peak at 3.7 ppm — which protons, why that shift?',
       'What would the spectrum look like if the reaction stopped at the intermediate?'],
      'Maps signal → structure and predicts the intermediate’s spectrum.', 'Assigns peaks from a table.'),
    dim('practical', 'Practical & safety rationale', 'Why this workup or quench; what the hazard actually is.',
      ['What is the actual hazard in this step, and what does the quench prevent?'],
      'Names the specific hazard and the mechanism of the quench.', 'Reproduces a generic safety paragraph.'),
    dim('perturbation', 'Perturbation', 'Solvent, temperature, leaving group, pH → predicted change.',
      ['Switch to a protic solvent — what happens to the rate and why?'],
      'Predicts direction and gives the mechanistic reason.', 'Says the reaction would be "affected".'),
    dim('error', 'Error analysis', 'Where the missing yield went and what observation supports that.',
      ['Which step lost the most material, and what did you observe that says so?'],
      'Points at a step and an observation.', 'Blames "human error".'),
  ],
  counterfactualLevers: [
    'room temperature instead of 0 °C', 'protic solvent', 'weaker base', 'wet reagent', 'stop the reaction early',
  ],
  tells: [
    'a textbook mechanism drawn but wrong for the substrate',
    'percent yield quoted to too many significant figures',
    'every peak assigned but the impurity peak ignored',
    'a generic safety section',
    'error analysis blaming "human error"',
  ],
  vocabularyTraps: ['stabilized', 'favorable', 'pure', 'quantitative', 'equilibrium shifts'],
  languageNote: 'Quote masses, shifts and conditions exactly as written, with units. Ask for recomputation rather than supplying the correct value.',
  sampleProbes: [
    'Your yield is 62%. Name the step where most of the 38% went, and the observation that supports that.',
    'Why is the addition run at 0 °C — what would you see at room temperature?',
    'The peak at 3.7 ppm — which protons, why that shift, and what would it look like if the reaction had stopped at the intermediate?',
    'Recompute the limiting reagent for me, out loud, from your masses.',
  ],
});
