import { definePack, detect, dim } from './kit';

/** Spec §3.3.1 — Computer Science / Software. */
export const csPack = definePack({
  id: 'cs',
  name: 'Computer Science / Software',
  shortName: 'CS',
  glyph: 'glyph-cs',
  tagline: 'Your code compiles. Can you defend line 23?',
  materialKinds: ['source files', 'notebooks', 'design docs', 'README + code', 'algorithm write-ups'],
  detect: detect(
    [['def ', 3], ['class ', 2], ['import ', 2], ['return ', 2], ['#include', 3], ['public static', 3],
     ['function', 2], ['const ', 1], ['async ', 2], ['O(n', 3], ['complexity', 2], ['runtime', 1],
     ['algorithm', 2], ['refactor', 2], ['unit test', 2], ['pull request', 2]],
    [['\\bfor\\s*\\(', 2], ['\\bwhile\\s*\\(', 2], ['=>\\s*\\{', 2], ['\\b[a-z_]+\\.[a-z_]+\\(', 1]],
    ['.py', '.js', '.ts', '.tsx', '.java', '.cpp', '.c', '.go', '.rs', '.rb', '.cs'],
    ['python', 'js', 'javascript', 'ts', 'typescript', 'java', 'cpp', 'c', 'go', 'rust', 'sql'],
  ),
  dimensions: [
    dim('design', 'Design rationale', 'Why this data structure, algorithm or decomposition.',
      ['Name the property of the problem that made this the right choice.',
       'Ask what the code would look like if that property did not hold.'],
      'Names the property and the alternative it beats.', '"It\'s the standard way."'),
    dim('alternatives', 'Alternatives rejected', 'What else could have worked, and why not here.',
      ['Propose a plausible alternative and demand the cost.',
       'Ask for the input size where the choice starts to matter.'],
      'Gives the concrete cost of the alternative on this input.', 'Says the alternative is "less efficient" with no quantity.'),
    dim('invariants', 'Correctness & invariants', 'What is true at each point; loop invariants; pre/post-conditions.',
      ['Trace it on a tiny input, out loud.', 'Move one line and ask what breaks.'],
      'States the invariant and shows where it is established and preserved.', 'Re-narrates the code line by line.'),
    dim('edges', 'Edge & failure behaviour', 'Empty input, duplicates, overflow, unicode, concurrency, malformed input.',
      ['Name two exceptions that can actually reach this handler.',
       'Ask what the function returns on the empty case and whether the caller can tell.'],
      'Names reachable failures and what the caller can distinguish.', 'Claims it "handles edge cases".'),
    dim('complexity', 'Complexity & resource', 'Time and space, and where in the code each term is paid.',
      ['Walk me through where each term of the bound is paid.',
       'Ask where the real bottleneck is versus the asymptotic one.'],
      'Points at the lines that pay each term.', 'Quotes a bound from memory.'),
    dim('provenance', 'Provenance of specifics', 'This constant, flag, regex, library call, magic number.',
      ['Where did this specific value come from?', 'What happens if it is off by one?'],
      'Explains the origin and the sensitivity.', '"It seemed to work."'),
    dim('testing', 'Testing & verification', 'How they know it works; the test that would break it.',
      ['Name the test you did not write that would fail.',
       'Ask what is currently untested and why that is acceptable.'],
      'Names a specific breaking input and the untested surface.', '"I tested it and it worked."'),
    dim('change', 'Change response', 'Requirement shifts: what changes and what does not.',
      ['Scale the input by 1000 — what is the first thing to break?',
       'Add a new constraint and ask which module absorbs it.'],
      'Separates what is stable from what is coupled to the assumption.', 'Says it would "need refactoring".'),
  ],
  counterfactualLevers: [
    'input ×1000', 'adversarial or duplicated input', 'empty input', 'swap the data structure',
    'forbid a library', 'require streaming / constant memory', 'make it concurrent', 'change language',
  ],
  tells: [
    'textbook-phrased comments on obvious lines',
    'idioms above the rest of the code’s level (lru_cache, walrus, generics, nested comprehensions)',
    'a docstring on every function in a 40-line script',
    'blanket `except Exception: pass`',
    'helper decomposition the author cannot motivate',
    'complexity claims written in comments',
    'defensive checks the assignment never asked for',
    'perfectly uniform naming', 'production-grade logging in homework',
  ],
  vocabularyTraps: ['efficient', 'O(n)', 'clean', 'modular', 'handles edge cases', 'thread-safe', 'idempotent'],
  languageNote: 'Quote code verbatim with line references. Keep identifiers exactly as written. Probes may ask the student to trace on a named tiny input.',
  sampleProbes: [
    'Line 23 uses `deque.popleft()`. Swapping it for `list.pop(0)` gives identical output. What actually changes, and at roughly what input size would a grader notice?',
    'You chose BFS here. Name the property of this problem that makes BFS correct, and one input where you would need Dijkstra.',
    'Your `visited` set is updated on enqueue, not dequeue. What goes wrong if you move it — trace a 3-node cycle.',
    'You catch `Exception` on line 40 and return `None`. Name two exceptions that can actually reach that line.',
    'There is a `# O(V+E)` comment. Walk me through where each of V and E is paid.',
  ],
});
