import { definePack, detect, dim } from './kit';

/** Spec §3.3.8 — Clinical Research Methods & Epidemiology. */
export const epiPack = definePack({
  id: 'epi',
  name: 'Clinical Research & Epidemiology',
  shortName: 'Epi',
  glyph: 'glyph-epi',
  tagline: 'You adjusted for three things. Draw me the DAG.',
  materialKinds: ['protocol drafts', 'critical appraisals', 'study designs', 'power calculations', 'journal-club summaries'],
  detect: detect(
    [['case-control', 4], ['cohort study', 4], ['RCT', 4], ['odds ratio', 4], ['hazard ratio', 4],
     ['confound', 4], ['intention-to-treat', 4], ['blinding', 3], ['incidence', 3], ['prevalence', 3],
     ['sample size', 3], ['selection bias', 4], ['attrition', 3], ['randomis', 3], ['randomiz', 3]],
    [['\\bOR\\s*[=:]\\s*\\d', 3], ['\\bRR\\s*[=:]\\s*\\d', 3], ['\\bHR\\s*[=:]\\s*\\d', 3], ['\\bn\\s*=\\s*\\d{2,}', 2]],
  ),
  dimensions: [
    dim('design', 'Design choice', 'Why this design for this question; what was traded away.',
      ['Why cohort and not case-control here — and what did you give up?'],
      'States the trade explicitly.', 'Says the design is "appropriate".'),
    dim('bias', 'Bias specific to this design', 'Which biases actually threaten THIS study.',
      ['Of the biases you listed, which one would move your estimate most, and in which direction?'],
      'Ranks biases by consequence and direction.', 'Lists every textbook bias with equal weight.'),
    dim('measure', 'Measure interpretation', 'RR vs OR vs HR vs NNT against the baseline risk.',
      ['Convert your OR into what it means for a patient at the control-group baseline risk.'],
      'Converts correctly and states the baseline.', 'Reads an OR as if it were an RR.'),
    dim('power', 'Sample size / power provenance', 'Which input drives n; sensitivity to each assumption.',
      ['Which single assumption, if wrong by 20%, changes n the most?'],
      'Identifies the dominant input.', 'Quotes n from software output.'),
    dim('analysis', 'Analysis choice', 'ITT vs per-protocol; adjustment set justified causally.',
      ['Which of your adjustment variables is a confounder, and is any of them a mediator or collider?'],
      'Reasons about the causal structure, not the variable list.', '"We adjusted for confounders."'),
    dim('counterfactual', 'Counterfactual', 'Attrition doubles; exposure misclassified non-differentially.',
      ['Non-differential exposure misclassification — which way does your estimate move?'],
      'Predicts the direction and says why.', 'Says the result would be "less reliable".'),
    dim('causal', 'Causal language discipline', 'What the design licenses them to say.',
      ['Which sentence in your conclusion overstates what this design supports?'],
      'Finds and rewrites their own overstatement.', 'Uses association and effect interchangeably.'),
  ],
  counterfactualLevers: [
    'double the attrition', 'misclassify exposure non-differentially', 'remove randomisation',
    'change the outcome to a surrogate',
  ],
  tells: [
    'every textbook bias listed with equal weight',
    '"confounders were adjusted for" without which or why',
    'an OR read as an RR',
    'power numbers not derivable from the stated assumptions',
    '"association" and "effect" used interchangeably',
  ],
  vocabularyTraps: ['adjusted', 'controlled', 'significant', 'causal', 'generalizable'],
  languageNote: 'Quote the student’s own design description and numbers. Ask for derivation and direction of bias, never supply a corrected estimate.',
  sampleProbes: [
    'You adjusted for age, sex and smoking. Talk me through the DAG: which is a confounder here, and is any of them a mediator or collider?',
    'Convert your OR of 2.4 into what it means for a patient, given the baseline risk in your control group.',
    'Your power calculation gives n = 212. Which single assumption, if wrong by 20%, changes n the most?',
    'Why cohort and not case-control for this question — and what did you give up?',
  ],
});
