import { definePack, detect, dim } from './kit';

/** Spec §3.3.4 — Mathematics & Proof. */
export const mathPack = definePack({
  id: 'math',
  name: 'Mathematics & Proof',
  shortName: 'Math',
  glyph: 'glyph-math',
  tagline: 'You wrote "clearly". Show me.',
  materialKinds: ['proofs', 'problem sets', 'derivations', 'LaTeX'],
  detect: detect(
    [['\\begin{proof}', 4], ['QED', 3], ['∎', 4], ['lemma', 3], ['theorem', 3], ['WLOG', 4],
     ['suppose', 2], ['induction', 3], ['converge', 2], ['∀', 3], ['∃', 3], ['\\frac', 2], ['iff', 2]],
    [['\\bfor all\\b', 2], ['\\bthere exists\\b', 2], ['\\bhence\\b', 1], ['\\$[^$]+\\$', 2]],
    ['.tex'],
    ['latex', 'tex'],
  ),
  dimensions: [
    dim('justification', 'Step justification', 'Which theorem or definition licenses line k.',
      ['Unpack this "clearly".', 'State the theorem you invoked with all of its hypotheses.'],
      'Names the licensing result and checks its hypotheses here.', 'Repeats the line more slowly.'),
    dim('hypotheses', 'Hypothesis necessity', 'Where each assumption is used.',
      ['Delete this hypothesis — what is the first line that becomes false?'],
      'Points at the exact line that fails.', 'Says the hypothesis is "needed for the theorem".'),
    dim('strategy', 'Strategy choice', 'Why induction not contradiction; why this construction.',
      ['What does a direct attempt run into?'],
      'Describes the obstruction the chosen strategy avoids.', '"It is the usual approach."'),
    dim('definitions', 'Definitions & boundary examples', 'Restate in own words; produce an object on the boundary.',
      ['Give me an object that only just satisfies this definition.'],
      'Produces a boundary object and says why it is on the boundary.', 'Recites the definition.'),
    dim('counterexample', 'Counterexample generation', 'A false lookalike statement and its smallest counterexample.',
      ['Give me a false statement that looks like this theorem.'],
      'Produces a minimal counterexample and explains the failing hypothesis.', 'Cannot perturb the statement.'),
    dim('generalize', 'Generalise / specialise', 'n = 0, infinite case, non-abelian, non-compact.',
      ['Does it hold in the infinite case? Where does the proof break?'],
      'Identifies the step that needs finiteness.', 'Guesses yes or no with no line reference.'),
    dim('provenance', 'Provenance of choices', 'Where ε/3 came from; why this lemma; why this bound.',
      ['What goes wrong with ε/2 — or would it work? Show me the deciding line.'],
      'Traces the constant back to the line that consumes it.', '"That is how it is usually written."'),
  ],
  counterfactualLevers: [
    'delete a hypothesis', 'change ε', 'change the domain (ℝ→ℚ, finite→infinite, abelian→non-abelian)',
    'replace "similarly" with "do it"',
  ],
  tells: [
    'flawless notation with "clearly" or "it follows" at exactly the hard step',
    'invoking a heavier theorem than needed',
    '"the other case is similar", never executed',
    'quantifier hygiene inconsistent with the student’s earlier work',
    'an over-general lemma stated then used for one trivial case',
  ],
  vocabularyTraps: ['trivially', 'by definition', 'WLOG', 'by compactness', 'similarly'],
  languageNote: 'Quote the proof line verbatim including notation. Refer to lines by their number or by their first few symbols.',
  sampleProbes: [
    'Point to the exact line where you used that f is continuous. Delete that hypothesis — what is the first line that becomes false?',
    'You chose ε/3. What goes wrong with ε/2 — or would it work? Show me the line that decides.',
    'State the theorem you invoked at line 5 with all its hypotheses, then show me each one holds here.',
    'Give me a false statement that looks like this theorem, and the smallest counterexample.',
    'You wrote "the case n = 1 is similar." Do it now, out loud.',
  ],
});
