import { definePack, detect, dim } from './kit';

/** Spec §3.3.6 — Machine Learning. */
export const mlPack = definePack({
  id: 'ml',
  name: 'Machine Learning',
  shortName: 'ML',
  glyph: 'glyph-ml',
  tagline: '94% accuracy on a 90/10 split. What does the baseline get?',
  materialKinds: ['notebooks', 'experiment reports', 'model cards', 'Kaggle-style write-ups'],
  detect: detect(
    [['train_test_split', 4], ['epoch', 3], ['learning rate', 3], ['overfit', 3], ['sklearn', 4],
     ['torch', 3], ['tensorflow', 3], ['embedding', 3], ['transformer', 3], ['validation set', 3],
     ['confusion matrix', 4], ['F1', 3], ['AUC', 3], ['cross-validation', 3], ['fine-tun', 3]],
    [['\\bacc(uracy)?\\s*[:=]\\s*0?\\.\\d+', 3], ['\\blr\\s*=\\s*\\d', 3], ['\\bbatch[_ ]size\\b', 3]],
    ['.ipynb', '.py'],
    ['python'],
  ),
  dimensions: [
    dim('baseline', 'Model choice vs baseline', 'What the simplest baseline scores, and whether they beat it.',
      ['What does predicting the majority class get? Which number shows you beat it?'],
      'Knows the trivial baseline and the margin over it.', 'Reports a headline metric with no reference point.'),
    dim('leakage', 'Pipeline & leakage', 'Split timing, scaler/encoder fit scope, target and temporal leakage.',
      ['Your scaler is fit before the split. Which number is contaminated, and in which direction?'],
      'Identifies the contaminated number and the direction of the bias.', 'Says the pipeline "follows best practice".'),
    dim('metric', 'Metric appropriateness', 'The metric that reflects the costly error for this task.',
      ['Which error costs more here, and which metric reflects that?'],
      'Ties the metric to the asymmetric cost.', 'Reports every metric available.'),
    dim('hyper', 'Hyperparameter provenance', 'Which were searched, over what range, what the worst setting looked like.',
      ['Which of these did you actually search, and what did the worst setting look like?'],
      'Describes the search and the failure end of it.', 'Calls defaults "tuned".'),
    dim('diagnosis', 'Overfitting / failure diagnosis', 'What the curves show; what a specific confusion cell means.',
      ['Point at the costly cell of your confusion matrix and tell me who those cases are.'],
      'Reads the specific cell as real-world cases.', 'Shows the matrix and moves on.'),
    dim('shift', 'Distribution counterfactual', 'Class prior shifts, feature removed, data drift.',
      ['If the minority class arrived at 30%, which reported numbers would you still trust?'],
      'Names which metrics are prior-dependent.', 'Assumes all numbers transfer.'),
    dim('honesty', 'Evaluation honesty', 'Validation vs test discipline, seeds, variance across runs.',
      ['How many times did you look at the test set?'],
      'Is explicit about seeds, variance and test-set discipline.', 'Reports a single number with no variance.'),
  ],
  counterfactualLevers: [
    'minority class 10% → 30%', 'remove the top feature', 'shift the time split',
    'run with a different seed', 'ten times less data',
  ],
  tells: [
    'scaler fit before the split with no discussion',
    'defaults described as "tuned"',
    'every metric reported',
    'a confusion matrix shown but the costly cell never discussed',
    'unused imports', '"97% accuracy" on imbalanced data',
    'architecture description above the level of the code',
  ],
  vocabularyTraps: ['overfitting', 'regularization', 'generalizes', 'state of the art', 'tuned', 'robust'],
  languageNote: 'Quote code and reported metrics verbatim. Ask for the number behind the number, never supply a corrected result.',
  sampleProbes: [
    'Your scaler is fit before the train/test split. Which number in your results table is contaminated by that, and in which direction?',
    'You report 94% accuracy on a 90/10 class problem. What does predicting the majority class get, and which number shows you beat it?',
    'lr = 3e-4 and batch 64. Which did you actually search over, and what did the worst setting look like?',
    'If deployment data arrived with the minority class at 30%, which of your reported numbers would you still trust?',
  ],
});
