import { definePack, detect, dim } from './kit';

/** Spec §3.3.5 — Statistics & Data Analysis. */
export const statsPack = definePack({
  id: 'stats',
  name: 'Statistics & Data Analysis',
  shortName: 'Stats',
  glyph: 'glyph-stats',
  tagline: 'df = 47. Reconstruct it.',
  materialKinds: ['analysis reports', 'R / Python notebooks with output', 'regression tables', 'survey analyses'],
  detect: detect(
    [['p-value', 3], ['confidence interval', 3], ['regression', 3], ['t-test', 3], ['ANOVA', 3],
     ['coefficient', 2], ['residual', 3], ['lm(', 4], ['glm(', 4], ['statsmodels', 4], ['scipy.stats', 4],
     ['R²', 3], ['heteroske', 4], ['multicollinear', 3], ['Likert', 3]],
    [['\\bp\\s*[<>=]\\s*0?\\.\\d+', 3], ['\\bdf\\s*=\\s*\\d+', 4], ['\\bβ\\d?\\s*=', 3], ['\\bCI\\b', 2]],
    ['.R', '.Rmd', '.ipynb'],
    ['r', 'python'],
  ),
  dimensions: [
    dim('choice', 'Test/model choice vs alternatives', 'Why this test for this data shape and this question.',
      ['What would you run instead, and what in your conclusions would change?'],
      'Ties the choice to the data shape and the question.', 'Names the test the course used most recently.'),
    dim('assumptions', 'Assumptions', 'Which ones matter here, how checked, what changes if violated.',
      ['Which assumption, if violated here, would actually move your conclusion?'],
      'Ranks assumptions by consequence for this dataset.', '"All assumptions were checked and met."'),
    dim('interpretation', 'Interpretation', 'A coefficient, CI or p-value read aloud so a non-statistician can act.',
      ['Read this coefficient aloud as a sentence for the client, with units and direction.'],
      'Gives units, direction and uncertainty in plain language.', 'Says the result is "significant".'),
    dim('handling', 'Data handling decisions', 'Missing data, outliers, transforms, categorical coding.',
      ['What did you do with the missing values, and which way does that bias the estimate?'],
      'States the decision and its directional consequence.', 'Does not mention the decision at all.'),
    dim('provenance', 'Provenance of numbers', 'Reconstruct df, n, an SE, a p-value from the design.',
      ['Reconstruct your df from your sample and model.'],
      'Derives the number live from the design.', 'Reads it off the output.'),
    dim('counterfactual', 'Counterfactual on data', 'n doubles, top point removed, log-transform.',
      ['Remove the single largest data point — which of your conclusions survive?'],
      'Predicts which conclusions are fragile and why.', 'Says results would be "similar".'),
    dim('limits', 'Inference limits', 'Association vs cause; the population the claim applies to; multiple comparisons.',
      ['Which population does this estimate actually apply to?'],
      'Bounds the claim to the sampled population.', 'Generalises freely.'),
  ],
  counterfactualLevers: [
    'remove the largest point', 'double n', 'violate normality', 'change the outcome to Likert',
    'add a confounder', 'apply multiple-testing correction',
  ],
  tells: [
    'p-values to four decimals with a canned interpretation',
    '"all assumptions were checked and met"',
    'a full regression table reproduced with no single coefficient discussed',
    '"significant" used ambiguously',
    'a sophisticated method (mixed models, bootstrap) with novice interpretation',
  ],
  vocabularyTraps: ['significant', 'controlled for', 'robust', 'normally distributed', 'correlated'],
  languageNote: 'Quote the exact numbers from the student’s output. Ask for reconstruction, never supply the corrected value.',
  sampleProbes: [
    'Your df is 47. Reconstruct that number from your sample and model.',
    'You ran a t-test on Likert scores. Defend it, or tell me what you would run instead and what in your conclusions would change.',
    'Read β₂ = −0.31 aloud as a sentence for the client, including units and uncertainty.',
    'Remove the single largest data point — which of your three conclusions survive?',
  ],
});
